<a href="https://colab.research.google.com/github/moggyyy4u/MiltonMog/blob/main/Pandas_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving titanic.csv to titanic.csv

In [ ]:
import pandas as pd

df = pd.read_csv('Crop Production data.csv')
print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: 'Crop Production data.csv'

In [ ]:
import pandas as pd

df = pd.read_csv('Crop Production data.csv')  # or use your DataFrame
print(df.head())     # Shows the first 5 rows
print(df.info())     # Data types + missing values summary
print(df.describe()) # Summary statistics for numeric columns

            State_Name    District_Name  Crop_Year       Season  \
0  ANDAMAN AND NICOBAR  NICOBAR ISLANDS       2000  Kharif
1  ANDAMAN AND NICOBAR  NICOBAR ISLANDS       2000  Kharif
2  ANDAMAN AND NICOBAR  NICOBAR ISLANDS       2000  Kharif
3  ANDAMAN AND NICOBAR  NICOBAR ISLANDS       2000  Whole Year
4  ANDAMAN AND NICOBAR  NICOBAR ISLANDS       2000  Whole Year

                  Crop    Area  Production
0             Arecanut  1254.0      2000.0
1  Other Kharif pulses     2.0         1.0
2                 Rice   102.0       321.0
3               Banana   176.0       641.0
4            Cashewnut   720.0       165.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246091 entries, 0 to 246090
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   State_Name     246091 non-null  object
 1   District_Name  246091 non-null  object
 2   Crop_Year      246091 non-null  int64
 3   Season         246091 non-null  object
 4   Crop           246091 non-null  object
 5   Area           246091 non-null  float64
 6   Production     242361 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.1+ MB
None
           Crop_Year          Area    Production
count  246091.000000  2.460910e+05  2.423610e+05
mean     2005.643018  1.200282e+04  5.825034e+05
std         4.952164  5.052340e+04  1.706581e+07
min      1997.000000  4.000000e-02  0.000000e+00
25%      2002.000000  8.000000e+01  8.800000e+01
50%      2006.000000  5.820000e+02  7.290000e+02
75%      2010.000000  4.392000e+03  7.023000e+03
max      2015.000000  8.580100e+06  1.250800e+09

In [ ]:
print (df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246091 entries, 0 to 246090
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   State_Name     246091 non-null  object
 1   District_Name  246091 non-null  object
 2   Crop_Year      246091 non-null  int64
 3   Season         246091 non-null  object
 4   Crop           246091 non-null  object
 5   Area           246091 non-null  float64
 6   Production     242361 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.1+ MB
None

In [ ]:
df.isnull().sum()

State_Name       0
District_Name    0
Crop_Year        0
Season           0
Crop             0
Area             0
Production       0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['Season']=df["Season"].str.strip()

In [ ]:
df['Crop'].unique()

array(['Arecanut', 'Other Kharif pulses', 'Rice', 'Banana', 'Cashewnut',
       'Coconut ', 'Dry ginger', 'Sugarcane', 'Sweet potato', 'Tapioca',
       'Black pepper', 'Dry chillies', 'other oilseeds', 'Turmeric',
       'Maize', 'Moong(Green Gram)', 'Urad', 'Arhar/Tur', 'Groundnut',
       'Sunflower', 'Bajra', 'Castor seed', 'Cotton(lint)', 'Horse-gram',
       'Jowar', 'Korra', 'Ragi', 'Tobacco', 'Gram', 'Wheat', 'Masoor',
       'Sesamum', 'Linseed', 'Safflower', 'Onion', 'other misc. pulses',
       'Samai', 'Small millets', 'Coriander', 'Potato',
       'Other  Rabi pulses', 'Soyabean', 'Beans & Mutter(Vegetable)',
       'Bhindi', 'Brinjal', 'Citrus Fruit', 'Cucumber', 'Grapes', 'Mango',
       'Orange', 'other fibres', 'Other Fresh Fruits', 'Other Vegetables',
       'Papaya', 'Pome Fruit', 'Tomato', 'Mesta', 'Cowpea(Lobia)',
       'Lemon', 'Pome Granet', 'Sapota', 'Cabbage', 'Rapeseed &Mustard',
       'Peas  (vegetable)', 'Niger seed', 'Bottle Gourd', 'Varagu',
       'Garlic', 'Ginger', 'Oilseeds total', 'Pulses total', 'Jute',
       'Peas & beans (Pulses)', 'Blackgram', 'Paddy', 'Pineapple',
       'Barley', 'Sannhamp', 'Khesari', 'Guar seed', 'Moth',
       'Other Cereals & Millets', 'Cond-spcs other', 'Turnip', 'Carrot',
       'Redish', 'Arcanut (Processed)', 'Atcanut (Raw)',
       'Cashewnut Processed', 'Cashewnut Raw', 'Cardamom', 'Rubber',
       'Bitter Gourd', 'Drum Stick', 'Jack Fruit', 'Snak Guard', 'Tea',
       'Coffee', 'Cauliflower', 'Other Citrus Fruit', 'Water Melon',
       'Total foodgrain', 'Kapas', 'Colocosia', 'Lentil', 'Bean',
       'Jobster', 'Perilla', 'Rajmash Kholar', 'Ricebean (nagadal)',
       'Ash Gourd', 'Beet Root', 'Lab-Lab', 'Ribed Guard', 'Yam',
       'Pump Kin', 'Apple', 'Peach', 'Pear', 'Plums', 'Litchi', 'Ber',
       'Other Rabi pulses', 'Peas (vegetable)', 'Other Dry Fruit',
       'Jute & mesta'], dtype=object)

'Rice', 'Banana','Maize','Wheat','Tea','Coffee','Pineapple','Apple','Peach','Pear','Tomato','Bean','Yam','Garlic','Ginger'

In [ ]:
selected_crops=['Rice', 'Banana','Maize','Wheat','Tea','Coffee','Pineapple','Apple','Peach','Pear','Tomato','Bean','Yam','Garlic','Ginger']
df1=df[df['Crop'].isin(selected_crops)]
df1

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
2,ANDAMAN AND NICOBAR,NICOBAR ISLANDS,2000,Kharif,Rice,102.0,321.00
3,ANDAMAN AND NICOBAR,NICOBAR ISLANDS,2000,Whole Year,Banana,176.0,641.00
12,ANDAMAN AND NICOBAR,NICOBAR ISLANDS,2001,Kharif,Rice,83.0,300.00
18,ANDAMAN AND NICOBAR,NICOBAR ISLANDS,2002,Kharif,Rice,189.2,510.84
20,ANDAMAN AND NICOBAR,NICOBAR ISLANDS,2002,Whole Year,Banana,213.0,1278.00
...,...,...,...,...,...,...,...
246058,West Bengal,PURULIYA,2014,Autumn,Rice,264.0,721.00
246084,West Bengal,PURULIYA,2014,Rabi,Wheat,1622.0,3663.00
246085,West Bengal,PURULIYA,2014,Summer,Maize,325.0,2039.00
246086,West Bengal,PURULIYA,2014,Summer,Rice,306.0,801.00
246089,West Bengal,PURULIYA,2014,Winter,Rice,279151.0,597899.00

In [ ]:
features = df1.drop(columns='Production')
features

,State_Name,District_Name,Crop_Year,Season,Crop,Area
2,ANDAMAN AND NICOBAR,NICOBAR ISLANDS,2000,Kharif,Rice,102.0
3,ANDAMAN AND NICOBAR,NICOBAR ISLANDS,2000,Whole Year,Banana,176.0
12,ANDAMAN AND NICOBAR,NICOBAR ISLANDS,2001,Kharif,Rice,83.0
18,ANDAMAN AND NICOBAR,NICOBAR ISLANDS,2002,Kharif,Rice,189.2
20,ANDAMAN AND NICOBAR,NICOBAR ISLANDS,2002,Whole Year,Banana,213.0
...,...,...,...,...,...,...
246058,West Bengal,PURULIYA,2014,Autumn,Rice,264.0
246084,West Bengal,PURULIYA,2014,Rabi,Wheat,1622.0
246085,West Bengal,PURULIYA,2014,Summer,Maize,325.0
246086,West Bengal,PURULIYA,2014,Summer,Rice,306.0
246089,West Bengal,PURULIYA,2014,Winter,Rice,279151.0

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ehe.fit_transform(features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 266652 stored elements and shape (44442, 20986)>

In [ ]:
features

,State_Name,District_Name,Crop_Year,Season,Crop,Area
2,ANDAMAN AND NICOBAR,NICOBAR ISLANDS,2000,Kharif,Rice,102.0
3,ANDAMAN AND NICOBAR,NICOBAR ISLANDS,2000,Whole Year,Banana,176.0
12,ANDAMAN AND NICOBAR,NICOBAR ISLANDS,2001,Kharif,Rice,83.0
18,ANDAMAN AND NICOBAR,NICOBAR ISLANDS,2002,Kharif,Rice,189.2
20,ANDAMAN AND NICOBAR,NICOBAR ISLANDS,2002,Whole Year,Banana,213.0
...,...,...,...,...,...,...
246058,West Bengal,PURULIYA,2014,Autumn,Rice,264.0
246084,West Bengal,PURULIYA,2014,Rabi,Wheat,1622.0
246085,West Bengal,PURULIYA,2014,Summer,Maize,325.0
246086,West Bengal,PURULIYA,2014,Summer,Rice,306.0
246089,West Bengal,PURULIYA,2014,Winter,Rice,279151.0

In [ ]:
ehe=OneHotEncoder()